---

# ansible-playbook -K -D -i inventory/hosts.yml playbook.yml

- name: Apache2
  hosts: all   # should be limited to web-servers
  become: true
  gather_facts: yes
  roles:
    - ansibleguy.infra_apache
