---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

collections:
  - name: 'community.crypto'
  - name: 'community.general'

roles:
  - src: 'ansibleguy.infra_certs'
