---

- name: Converge
  hosts: all
  vars:
    apache:
      sites:
        test1:
          domain: 'apache2.test.ansibleguy.net'

          ssl:
            mode: 'snakeoil'
            cert:
              cn: 'Apache2'
              org: 'AnsibleGuy Test'
              email: 'testmaster@ansibleguy.net'

  roles:
    - ansibleguy.infra_apache
