---

# ports will be left configured since I found no clean way to manage them statefully
# also: the web-root will be left as-is

- name: "Apache | Debian | Config | Site '{{ name }}' | Removing/Disabling site"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/apache2/sites-enabled/site_{{ name }}.conf"
    - "/etc/apache2/sites-available/site_{{ name }}.conf"
    - "{{ APACHE_CONFIG.ssl.path }}/{{ name }}.key"
    - "{{ APACHE_CONFIG.ssl.path }}/{{ name }}.crt"
    - "{{ APACHE_CONFIG.ssl.path }}/{{ name }}.chain.crt"
    - "{{ APACHE_CONFIG.ssl.path }}/{{ name }}.fullchain.crt"
