---

- name: "Apache | Debian | LetsEncrypt Certbot | Creating alternative name string (1/3)"
  ansible.builtin.set_fact:
    _aliases: "{{ site.aliases | join(' --domain ') }}"
  when: apache_aliases | length > 0

- name: "Apache | Debian | LetsEncrypt Certbot | Creating alternative name string (2/3)"
  ansible.builtin.set_fact:
    _apache_aliases: "{{ '--domain ' + _aliases }}"
  when: apache_aliases | length > 0

- name: "Apache | Debian | LetsEncrypt Certbot | Creating alternative name string (3/3)"
  ansible.builtin.set_fact:
    _apache_aliases: ''
  when: apache_aliases | length == 0

- name: debug
  ansible.builtin.debug:
    msg: "certbot certonly --apache -{{ APACHE_CONFIG.letsencrypt.verbosity }} --non-interactive --agree-tos --email {{ site.admin }} --cert-name {{ name }}
    --rsa-key-size {{ APACHE_CONFIG.letsencrypt.key_size }} --no-redirect --domain {{ site.domain }} {{ _apache_aliases }}"

- name: "Apache | Debian | LetsEncrypt Certbot | Starting certbot for domain '{{ site.domain }}'"
  ansible.builtin.shell: "certbot certonly --apache -{{ APACHE_CONFIG.letsencrypt.verbosity }} --non-interactive --agree-tos --email {{ site.admin }} --cert-name {{ name }}
  --rsa-key-size {{ APACHE_CONFIG.letsencrypt.key_size }} --no-redirect --domain {{ site.domain }} {{ _apache_aliases }}"
  ignore_errors: yes
